from __future__ import annotations

from egx_news_bot.models import NewsFeedConfig


DEFAULT_FEEDS: tuple[NewsFeedConfig, ...] = (
    NewsFeedConfig(
        name="Arab Finance Macroeconomy",
        url="https://www.arabfinance.com/en/rss/rssbycat/1",
        language="en",
        credibility=0.78,
        tags=("macro", "egypt", "economy"),
    ),
    NewsFeedConfig(
        name="Arab Finance Banking",
        url="https://www.arabfinance.com/en/rss/rssbycat/2",
        language="en",
        credibility=0.78,
        tags=("banks", "finance"),
    ),
    NewsFeedConfig(
        name="Arab Finance Real Estate",
        url="https://www.arabfinance.com/en/rss/rssbycat/3",
        language="en",
        credibility=0.78,
        tags=("real_estate", "tourism"),
    ),
    NewsFeedConfig(
        name="Arab Finance Energy",
        url="https://www.arabfinance.com/en/rss/rssbycat/6",
        language="en",
        credibility=0.78,
        tags=("energy",),
    ),
    NewsFeedConfig(
        name="Arab Finance Industries",
        url="https://www.arabfinance.com/en/rss/rssbycat/8",
        language="en",
        credibility=0.78,
        tags=("industrials",),
    ),
    NewsFeedConfig(
        name="Al Borsa News",
        url="https://www.alborsaanews.com/feed",
        language="ar",
        credibility=0.75,
        tags=("egypt", "market", "companies"),
    ),
    NewsFeedConfig(
        name="Daily News Egypt",
        url="https://www.dailynewsegypt.com/feed/",
        language="en",
        credibility=0.68,
        tags=("egypt", "business"),
    ),
    NewsFeedConfig(
        name="Daily News Egypt Business",
        url="https://www.dailynewsegypt.com/category/business/feed/",
        language="en",
        credibility=0.72,
        tags=("egypt", "business", "banks", "stock_market", "rates", "real_estate"),
    ),
    NewsFeedConfig(
        name="Enterprise AM",
        url="https://enterpriseam.com/feed/",
        language="en",
        credibility=0.76,
        tags=("macro", "business"),
    ),
    NewsFeedConfig(
        name="Economy Plus",
        url="https://economyplusme.com/feed/",
        language="ar",
        credibility=0.72,
        tags=("economy", "business"),
    ),
    NewsFeedConfig(
        name="Hapi Journal",
        url="https://hapijournal.com/feed/",
        language="ar",
        credibility=0.70,
        tags=("economy", "companies"),
    ),
    NewsFeedConfig(
        name="Youm7 Economy and Bourse",
        url="https://www.youm7.com/rss/SectionRss?SectionID=297&output=xml",
        language="ar",
        credibility=0.64,
        tags=("egypt", "economy", "market", "prices"),
    ),
    NewsFeedConfig(
        name="Masrawy Economy",
        url="https://www.masrawy.com/rss/feed/206/%D8%A5%D9%82%D8%AA%D8%B5%D8%A7%D8%AF",
        language="ar",
        credibility=0.64,
        tags=("egypt", "economy", "prices"),
    ),
    NewsFeedConfig(
        name="Masrawy Banking",
        url="https://www.masrawy.com/rss/feed/847/%D8%A3%D8%AE%D8%A8%D8%A7%D8%B1-%D8%A7%D9%84%D8%A8%D9%86%D9%88%D9%83",
        language="ar",
        credibility=0.66,
        tags=("egypt", "banks", "finance"),
    ),
    NewsFeedConfig(
        name="Amwal Al Ghad English",
        url="https://en.amwalalghad.com/feed/",
        language="en",
        credibility=0.74,
        tags=("egypt", "banks", "finance", "investment", "real_estate", "egx"),
    ),
    NewsFeedConfig(
        name="Egyptian Streets Business",
        url="https://egyptianstreets.com/category/business-technology/feed/",
        language="en",
        credibility=0.66,
        tags=("egypt", "business", "economy", "technology"),
    ),
    NewsFeedConfig(
        name="Invest-Gate Real Estate",
        url="https://invest-gate.me/feed/",
        language="en",
        credibility=0.66,
        tags=("egypt", "real_estate", "developers"),
    ),
    NewsFeedConfig(
        name="Egypt Oil & Gas",
        url="https://egyptoil-gas.com/feed/",
        language="en",
        credibility=0.68,
        tags=("egypt", "energy", "oil_gas", "petrochemicals"),
    ),
    NewsFeedConfig(
        name="Property Plus",
        url="https://propertypluseg.com/feed/",
        language="ar",
        credibility=0.62,
        tags=("egypt", "real_estate", "banks", "property"),
    ),
    NewsFeedConfig(
        name="Mubasher EGX English",
        url="http://feeds.mubasher.info/en/EGX/news",
        language="en",
        credibility=0.70,
        tags=("egx", "companies"),
        poll_interval_seconds=900,
    ),
)
